### PR TITLE
Fix mispell of again

### PR DESCRIPTION
**Pull request by craigallen**
Fix misspelling of again.

### CODE REVIEW

**Comment by salcode** [comment]
@allendesignco this is looking great. I apologize I missed something on the first pass.

You have 
`Fix #24`
at the end of your commit message, which is great except
the open issue is #1 (not #24)
therefore the last line should be
`Fix #1` instead.

Do __not__ close this PR.  Instead

If you run
```
git commit --amend
```
this will allow you to amend your last commit message.

Afterwards, you'll need to push those changes to GitHub
```
git push
```
which will automatically update this pull request (since it is based on the branch name and you'll be updating that branch)

You are right at the finish line on this.

**Comment by allendesignco** [comment]
Where do I run those commands?

**Comment by allendesignco** [comment]
Tried to do this in Terminal.  Not sure if it worked.

**Comment by salcode** [comment]
I don't think it did work, I'm still seeing the old commit message

image

Sorry, I had assumed you were using Terminal before.  What program are you using for Git?

**Pull request closed without merging**
